### PR TITLE
First Cut Sharing SDK

### PR DESCRIPTION
**Pull request by sojanpr**
First version of Android  sharing  SDK.
@aaustin @shortstuffsushi

### CODE REVIEW

**Comment by aaustin** [comment]
Really, really nice. A couple minor things.

- [ ] Can we add the negative slide out animation on minimize
- [ ] In the no-connection case, I believe in iOS, we use a default URL if the Branch link can't be created. This allows the user to initiate a share message/copy whether or not it's a fresh Branch link or not. Can you add a default URL option instead of just failing the share?
- [ ] In the no-connection case, can we just fill the message without a link if there's backup link?
- [ ] Should we return SHARE_WITH type in the onLinkShareResponse? I believe it's currently returning the package name of the app shared to?
- [ ] Can we show a short Toast that 'copied link to clipboard!' after copy is selected
- [ ] I'm not sure how to simulate slow connections, but if /v1/url takes a second or two, or there are retries, do we have some sort of network delay handing UI? I can see folks in India running into this problem quite a bit.
- [ ] Really nitpicky, but can we move the More options.. below the Copy link option?
- [ ] Is that the standard icon for Copy? Can we use a different one? Not sure where you got it, but if there's one in this style (http://fortawesome.github.io/Font-Awesome/icon/clipboard/) that'd be idea.

**Comment by sojanpr** [comment]
- [ ] Can we add the negative slide out animation on minimize
    -  Since we deploy SDK as jar we cannot add resource xml files. At this point window animations can 
         be set only with animation defined in resource xml.

- [ ] In the no-connection case, I believe in iOS, we use a default URL if the Branch link can't be created. 
This allows the user to initiate a share message/copy whether or not it's a fresh Branch link or not. Can you add a default URL option instead of just failing the share?
    -  Added an option for setting default url in builder. 

- [ ] In the no-connection case, can we just fill the message without a link if there's backup link?
     -  In no-connection case or any error the default url will be shared (if a default url is specified). 

- [ ] Should we return SHARE_WITH type in the onLinkShareResponse? I believe it's currently returning the package name of the app shared to?
     -  We are returning the Application Name(Facebook ,Twitter etc). Since we have  "more" option which
        shows all different application avaible on the device, not necessarily the selected app is defined in 
         SHARED_WITH always. 
 
- [ ] Can we show a short Toast that 'copied link to clipboard!' after copy is selected
     -  Changed toast text to 'copied link to clipboard!'

- [ ] I'm not sure how to simulate slow connections, but if /v1/url takes a second or two, or there are retries, do we have some sort of network delay handing UI? I can see folks in India running into this problem quite a bit.
     -  Slow connections case is tested on emulator. Emulator provides setting to specify connection speed
        and performance. The share dialog window will be up in disabled state until  the v1/url is respond in 
        order to prevent the activity context change by user. Devs can override this feature by calling
         `cancelSharingDialog()` 

- [ ] Really nitpicky, but can we move the More options.. below the Copy link option?
      -  More options moved to the bottom.

- [ ] Is that the standard icon for Copy? Can we use a different one? Not sure where you got it, but if there's one in this style (http://fortawesome.github.io/Font-Awesome/icon/clipboard/) that'd be idea.
      - The icons currently showing for "More" and "Copy link" are standard android icons for  "More" and 
         "Save". We cannot add resources to the SDK since we are deploying  Jar file. There is a "Copy" 
         Icon similar to the one shown in the link above but thats not available on all API levels.

**Comment by sojanpr** [comment]
Added a slide down animation when user selected an application on the closer dialog

**Comment by aaustin** [comment]
:+1: beautiful

**Comment by sojanpr** [comment]
Merged with master and conflicts resolved

**Pull request closed without merging**
