### PR TITLE
Enables gradle support for Android Studio and sonatype/maven push

### PR DESCRIPTION
**Pull request by SleeplessByte**
This will update the gradle definitions to comply with the currently supported versions. To add Branch-Android-SDK in android studio:

- Close your current project if any
- Import from Non-Android-Studio Project
- Select build.gradle in the root
- Wait
- Press: sync gradle build

The project should display as 2 modules automagically. You might want to consider changing from an Eclipse directory structure to the Android Studio directory studio as well.

### CODE REVIEW

**Comment by aaustin** [comment]
This won't be listed as a live Gradle module though right? The instructions you provide just make it easier to add

**Comment by SleeplessByte** [comment]
Exactly. You are thinking of the android to maven push. Do you want me to put that up as well?

**Comment by SleeplessByte** [comment]
This now replaces #27.

I inferred all the `gradle.properties` from that pull-request. Please check them.
If nothing is changed, this would be released as io.branch.sdk.android:library:1.1.8

## [Setup required](https://github.com/chrisbanes/gradle-mvn-push#2-update-your-home-gradleproperties)
**Update your home `gradle.properties`**

This will include the username and password to upload to the Maven server and so that they are kept local on your machine. The location defaults to `USER_HOME/.gradle/gradle.properties`.

It may also include your signing key id, password, and secret key ring file (for signed uploads). Signing is only necessary if you're putting release builds of your project on maven central.

````
NEXUS_USERNAME=yourusername
NEXUS_PASSWORD=yourpassword

signing.keyId=somesigningkeyid
signing.password=somesigningpassword
signing.secretKeyRingFile=~/.gnupg/secring.gpg
````

### How to get the signing key?

1. Generate one if not already done: `gpg --gen-key`
1. List them: `gpg --list-keys`
1. `XXXXXXXX/YYYYYYYY <date>`: `YYYYYYYY` is the id
1. Publish them if not already done: 
   * `gpg --keyserver hkp://keyserver.ubuntu.com --send-keys YYYYYYYY`
   * `gpg --keyserver hkp://pgp.mit.edu --send-keys YYYYYYYY`
1. Ensure they were published: 
    * ` gpg --keyserver hkp://pgp.mit.edu --search-keys johndoe@example.com # Use your email`

### Setup `signing.properties`
You will find a sample file in the android-sdk-testbed project. Obviously you don't want to check this into git.

## How to release a version
Make sure your `VersionName` and `VersionCode` are correct. Add `SNAPSHOT` in the name to make it a debug-build.

1. `gradle uploadArchives`
2. Check if it is signed. 
3. Check the gradle log. A 401 means your username/password was incorrect.

**Comment by qinweigong** [comment]
@SleeplessByte I've got everything (gradle.properties, gpg key published) setup. However, I am not sure what values I should put in signing.properties file.

STORE_FILE: is this same file path as ~/.gnupg/secring.gpg ?
STORE_PASSWORD: is this same as the NEXUS_PASSWORD ?
KEY_PASSWORD: is this same as the signing.password
KEY_ALIAS: is this same as the signing.keyId in gradle.properties file?

Thanks in advance!

**Comment by SleeplessByte** [comment]
Signing is only necessary if you're putting release builds. For a library it probably don't need to do that, as people will sign it when they include this in their app.

A release build application however is signed as described in [this guide](http://developer.android.com/tools/publishing/app-signing.html)

**Comment by qinweigong** [comment]
When I execute gradle uploadArchives I got 401 error :-(

Is it the nexusUsername/nexusPassword in my /Users/qinwei/.gradle/gradle.properties file?

I use the same username/pw to login to https://oss.sonatype.org/#stagingRepositories and it works!

**Comment by SleeplessByte** [comment]
@qinweigong I believe so. You can always (temporarily) try to add NEXUS_XXX to the project gradle.properties.

**Comment by qinweigong** [comment]
Oops, I know what went wrong. In the gradle.properties file I used nexusUsername/nexusPassword instead of NEXUS_USERNAME/NEXUS_PASSWORD. Changed them and now uploadArchives went through with a "BUILD SUCCESSFUL".

FYI, I modified the VERSION_NAME=1.2.9. However when I searched https://oss.sonatype.org/#nexus-search;quick~branch-android-sdk, I don't see the latest package there. Any advice?

**Comment by SleeplessByte** [comment]
I don't know how long it takes to propagate. If it went through, it really did go through. However the script [might have been cached](https://gradle.org/docs/current/userguide/tutorial_this_and_that.html#sec:caching). So you could try a run with ` --recompile-scripts`.

**Comment by SleeplessByte** [comment]
Hmmm. It's still not there. You might want to go ahead and contact them.

**Comment by qinweigong** [comment]
Yah, I just sent contacted them in Jira ticket.

https://issues.sonatype.org/browse/OSSRH-12715

**Comment by qinweigong** [comment]
Ha, I forgot that I needed to close and release the staging.

**Comment by qinweigong** [comment]
It's on prod Sonatype now! 1.2.9

**Comment by SleeplessByte** [comment]
Yay!

**Pull request merged**
