### PR TITLE
Initial Tests

### PR DESCRIPTION
**Pull request by qinweigong**

### CODE REVIEW

**Comment by qinweigong** [comment]
@aaustin

**Comment by qinweigong** [comment]
CircleCI test success is false. Currently all tests will pass their Android tests, and they are working on it.

<quote>
Hi,
We're currently working on revamping our android support to make it more robust and one thing we've noticed is that adb shell doesn't exit properly.
You might want to install fb-adb in your container and use that. It will be included in an upcoming container release on our side, but you can custom install it for now.
Hope that helps,
Rob.
</quote>
Their ETA is 3/12. Will add CircleCI integration to asana todo list.

**Comment by aaustin** [comment]
This is awesome!! :+1: Super excited. Can you document the outstanding tests you think we should run as a todo for the eventual Android hire?

**Comment by qinweigong** [comment]
I already added the todo list to Android Asana tasks.

**Pull request merged**
